server:
  port: 9001 #tomact服务端口

spring:
  application:
    name: goods
  datasource:    #设置数据库连接相关信息
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/changgou_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka   #这是eureka服务端的地址
    instance:
      prefer-ip-address: true   #以IP地址注册到服务中心，相互注册使用IP地址

feign:
  hystrix:
    enabled: true  #开启feign的hystrix支持,默认是false

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true  #如果enabled设置为false，则请求超时交给ribbon控制
        isolation:
          strategy: SEMAPHORE



